### ISSUE TITLE
navigator.xr.requestDevice is not a function

### ISSUE THREAD

**Issue by evdem** [barrykui/VRmol#8]
"Uncaught TypeError: navigator.xr.requestDevice is not a function" (WebVR.js:138) on my Oculus Go (Oculus browser) in VR mode. All works fine in standard 3D mode.

By the way, don't you like to add support for multi-frame data and animations?
https://www.ibiblio.org/e-notes/webxr/samples.htm. More comments?

Evgeny

**Comment by evdem** [comment]
I get this error in Oculus browser (Chrome based). It uses native WebXR. In Firefox Reality (with WebXR polyfill) VRmol works. Pictures are better than in VR GLmol but much slower. You can test your VRmol in Chrome on Android.

**Comment by kuixu** [comment]
Thanks for your feedback and appreciation. We are looking into this problem. And It would be pretty cool when supporting animations, especially for a molecule. 

BTW: You can try a new related work [ProteinVR](https://durrantlab.pitt.edu/protein-vr/)

**Comment by kuixu** [comment]
@evdem The error has been fixed, and the running web server has been upgraded based on the WebXR core API, which supports Chrome(>=81), Microsoft Edge (>=81). We test on VR devices from HTC VIVE and Windows Mixed Reality. Welcome to the new VRmol.

While for phone, Firefox Reality is still well supported, but currently, it seems that something wrong with WebXR on Chrome (version 81) on Android.
